### PR TITLE
Infer a speculation rule's source from the other keys

### LINKED ISSUE #169: Consider removing "source" from speculation rules objects
For ergonomics, it would be simpler to be able to write `{ "urls": [...] }` instead of `{ "source": "list", "urls": [...] }`.

This would only work if we think every future list source will have distinct, distinguishable keys which we could use to infer the source. So far, for all cases in the explainer, this is the case: none of the document-source rules use `"urls"`. (And I believe the opposite also holds, where none of the keys that are unique to document rules can be used in list rules.)

It's a bit constraining, but I think the ergonomic benefits would be substantial.

### PR DESCRIPTION
**Pull request by jeremyroman**
Fixes #169.

### CODE REVIEW

**Comment by jeremyroman** [comment]
What do you think? First commit is my first instinct (if present validate it as now, just allow it to be absent). Second was your slight preference (ignore it entirely).

Honestly I think I have a slight preference for the former but don't feel super strongly.

This is pretty trivial and I'd hope we can use a lightweight process if this makes sense to you.

**Comment by jeremyroman** [comment]
One case that ignoring it would break (that our unit tests caught) -- a catch-all could previously be written `{"source":"document"}` with no conditions, but that's not possible if implicit `"source"` is the only option. At least not unless we make `{}` also universal, which feels excessively weird.

**Review by domenic — APPROVED** [review]
I'm convinced, let's infer it!

Maybe also consider explainer updates in this PR?

**Review by domenic — APPROVED** [review]
Love it!!

**Pull request merged**
